image: node:lts-alpine3.12

cache:
  paths:
    - node_modules/

before_script:
  - test -e package.json && npm install

pages:
  stage: deploy
  script:
    - npm run build
    - mv _sites public
  artifacts:
    paths:
      - public
  only:
    - master

