name: ci

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

permissions:
  checks: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - name: Check out repository (push)
        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request_target' || github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}
        uses: actions/checkout@v2

      - name: Check out repository (pull_request_target)
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup node env 📦
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Upgrade npm ✨
        run: npm i -g npm@latest

      - name: Install dependencies 🚀
        run: npm ci --prefer-offline --no-audit --no-optional

      - name: Run linter
        run: npm run lint

      - name: Run test
        run: npm run test

      - name: Run build
        run: npm run build
